### ISSUE TITLE
Better way to replace Root

### ISSUE THREAD

**Issue by ai** [lahmatiy/postcss-csso#1]
```js
    return function (root, result) {
        var minified = csso.minify(root.toString(), options);
        result.root = postcss.parse(minified, result.opts);
    }
```

It is cleaner and also saves file name

**Comment by lahmatiy** [comment]
@ai Yep, I discovered this solution, but w/o options for parse. But I stuck with source map for now. I need to pass result source map to `csso`, but I have no access to `postcss` map-generator and don't know another way to get source map.

**Comment by lahmatiy** [comment]
Now it's using AST converting (postcss->csso->postcss) with no re-parsing. So problem with source maps is solved.

**Comment by ai** [comment]
Nice, AST converter is useful thing.
