### ISSUE TITLE
PostCSS 7

### ISSUE THREAD

**Issue by sectsect** [lahmatiy/postcss-csso#12]
PostCSS 7 released.
There are no real breaking changes. Node.js 4 has dropped.

**Comment by a-x-** [comment]
has any hews?

**Comment by a-x-** [comment]
Looks like there is postcss@7 fork: https://github.com/rikser123/postcss-csso

**Comment by a-x-** [comment]
I created npm package: [postcss-csso-7](https://npmjs.com/postcss-csso-7)
