### ISSUE TITLE
postcss.plugin was deprecated.

### ISSUE THREAD

**Issue by yhay81** [lahmatiy/postcss-csso#16]
A New warning occurs with postcss 8.0.

It says
```
postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

**Comment by lahmatiy** [comment]
Plugin migrated to PostCSS 8.0. It's now available as [5.0.0](https://github.com/lahmatiy/postcss-csso/releases/tag/v5.0.0)
