### ISSUE TITLE
Use with postcss.config.js?

### ISSUE THREAD

**Issue by brycewray** [lahmatiy/postcss-csso#22]
Is there any recommended procedure for using this in a `postcss.config.js` file, similar to how that’s done with other PostCSS minification plugins like postcss-clean or cssnano?

**Comment by lahmatiy** [comment]
There are no special recommendations, it works as any other plugin. You may setup postcss-csso in `postcss.config.js` like so:

```js
module.exports = {
    plugins: [
        require('postcss-csso')({
            // options if any
        })
    ]
};
```

I've added this example in README. Thanks for the question!

**Comment by brycewray** [comment]
@lahmatiy Thanks. I actually had already tried that, but must have gotten something wrong because I kept getting errors. Will give it another attempt.
